### PR TITLE
.do.select now fires change event

### PR DESCRIPTION
**Pull request by inca**
I guess we should also investigate other methods that interact with form controls.

### CODE REVIEW

**Comment by puzrin** [comment]
Is it a specific workaround for phantomjs bug?

**Comment by inca** [comment]
Values assigned directly to DOM do not trigger change events. The topic is discussed [here](http://stackoverflow.com/questions/5760873/trigger-change-event-when-setting-selects-value-with-val-function) (nevermind jQuery, it's all the same with vanilla JS).

Since Navit emulates user behavior, firing these events is important since client application often subscribe to them (e.g. for validation or even submitting).

**Comment by inca** [comment]
Apparently, we need to do the same with `do.check`.

**Comment by puzrin** [comment]
So, that's not a specific phantomjs hack, and will work the same way in slimerjs (when available) ?

**Comment by inca** [comment]
That is correct, yes.

**Pull request merged**
