### PR TITLE
A bunch of changes: .do.clear method, some docs, test for .do.upload

### PR DESCRIPTION
**Pull request by inca**

### CODE REVIEW

**Comment by puzrin** [comment]
Is `[.do].clear()` really needed as separate method? Do you know use cases?

If case is very rare, it probably worth to leave it for generic attributes manipulation call.

**Comment by inca** [comment]
The common case would be typing over existing values in inputs (e.g. when the form is already filled and you want to replace it with a new one).

**Comment by inca** [comment]
Also the technique of clearing contenteditable elements is a bit different (we remove all its children instead), whereas the actions are nearly identical from the user's point of view (e.g. Ctrl A -> Del or something similar).

**Comment by puzrin** [comment]
I understand. But is it really needed so often to create separate named method?
- We still can use `.set.attribute(selector, name, value)`. Also, i doubt that someone need to write tests without knowledge of field type.
- We can implement missed `.fill()`

I don't object against feature. Just try to understand the best way to keep api nice.

**Comment by puzrin** [comment]
If you say "i have a lot of test where this feature is needed", that will be enougth to merge.

**Comment by PublicFess** [comment]
Hi all.
I write tests without knowledge of field type. For example compose editor which depend div, not textarea or input. 
`.do.clear` is easier then `.set.attribute` or other methods and i have tests where this feature is needed.

**Comment by puzrin** [comment]
@PublicFess
1. current name can be a bit confusing with casper's api http://docs.casperjs.org/en/latest/modules/casper.html#clear for switchers.
2. Is `.fill()` method (when implemented) with override mode also not convenient for your tasks?

**Comment by PublicFess** [comment]
@puzrin 

Sorry, but I can not find `.fill` method in your source code.

**Comment by puzrin** [comment]
https://github.com/nodeca/navit/issues/1#issuecomment-95822582

**Comment by PublicFess** [comment]
@puzrin 

`.fill` method can solve part of my tasks. But if i have element such as `<input ng-change="foo()">` `.clear` method is a my way. 

I think that both of methods solve different tasks and they should be implement.

**Comment by puzrin** [comment]
Ok. I'm not frontent writer guru and can't argue. Let's accept it now.

**Comment by inca** [comment]
Sorry for the delay, @puzrin yeah, long story short, I have a lot of tests where `clear()` is needed :)

**Comment by inca** [comment]
Thanks for the merge :)

**Comment by inca** [comment]
I guess that's all for today :)

**Comment by puzrin** [comment]
Published. Enjoy!

**Pull request merged**
